language: python
services:
  - mongodb

python:
  - "3.4"
  - "3.5"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
  - pip install -r requirements.txt

before_script:
  - nvm install stable
  - npm install --global gulp
  - npm install --save-dev gulp
  - npm install --save-dev gulp-sass
  - npm install --save-dev gulp-babel
  - npm install --save-dev gulp-inject
  - npm install --save-dev gulp-uglify
  - npm install --save-dev gulp-uglify-inline
  - npm install --save-dev gulp-sourcemaps
  - npm install --save-dev gulp-jshint 
  - python setup.py prepare

script:
  - gulp
  - py.test --pyargs app --no-send
