language: python
services:
  - mongodb

python:
  - "3.4"
  - "3.5"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
  - pip install -r requirements.txt

before_script:
  - nvm install stable
  - npm install --global gulp
  - npm install gulp
  - npm install gulp-sass
  - npm install gulp-babel
  - npm install gulp-inject
  - npm install gulp-uglify
  - npm install gulp-uglify-inline
  - npm install gulp-sourcemaps
  - npm install gulp-jshint 
  - python setup.py prepare

script:
  - gulp
  - py.test --pyargs app --no-send
