language: python
services:
  - mongodb
python:
  - "3.4"
  - "3.5"
  - "nightly"
install:
  - pip install -r requirements.txt
before_script:
  - python setup.py prepare
script: py.test --pyargs app --no-send
