language: python

python:
  - "3.5"
  - "nightly"

install:
  - pip install -r requirements.txt

before_script:
  - nvm install stable
  - npm install --global gulp
  - npm install
  - gulp
  ###### Install the latest Redis ######
  - wget http://download.redis.io/releases/redis-stable.tar.gz
  - tar xzf redis-stable.tar.gz
  - cd redis-stable
  - make
  - echo 'daemonize yes' | src/redis-server -
  - cd ..
  ######################################

script:
  - py.test --pyargs app --no-send
